add apache configuration and system status

diff --git a/tools/privacyidea-diag b/tools/privacyidea-diag
--- a/tools/privacyidea-diag
+++ b/tools/privacyidea-diag
@@ -41,7 +41,12 @@ else
 fi
 
 OS=$(grep "^ID=" /etc/os-release | sed -e 's/^ID=//g' | tr -d '"')
-tempfile=$(mktemp --suff=.diag)
+
+diag_info=$(mktemp -d -t pi_diag_XXXXXXXXXX)
+tempfile="${diag_info}/privacyidea.config"
+timestamp=$(date +"%y-%m-%d")
+location="/tmp/${timestamp}_$(basename "$diag_info").tar.gz"
+
 
 log() {
 	echo "$1" >> "$tempfile"
@@ -49,6 +54,12 @@ log() {
 
 call_pi_manage() {
 	PRIVACYIDEA_CONFIGFILE=$PICFG pi-manage "$@"
+}
+
+upload_info() {
+	echo
+	echo "Please upload the diagnostics file and $location to your support team."
+	echo
 }
 
 get_os() {
@@ -71,14 +82,8 @@ get_pi_cfg() {
 current_db_revision() {
 	log
 	log "SECTION: current_db_revision"
-	log "============================="
+	log "============================"
 	call_pi_manage db current -d /opt/privacyidea/lib/privacyidea/migrations/ >> "$tempfile"
-}
-
-upload_info() {
-	echo
-	echo "Please upload the diagnostics file $tempfile to your support team."
-	echo
 }
 
 pi_versions() {
@@ -124,52 +129,6 @@ pi_config() {
 	call_pi_manage policy p_export >> "$tempfile"
 }
 
-pi_logfile() {
-	log
-	log "SECTION: privacyIDEA Logfile"
-	log "============================"
-	R=$( grep "^PI_LOGFILE" "$PICFG" | cut -d "=" -f2 | tr -d "\'\"" )
-	[ -f ${R} ] && cat ${R} >> $tempfile || echo "Could not read logfile ${R}" >> "$tempfile"
-}
-
-pi_auditlog() {
-	log
-	log "SECTION: privacyIDEA Auditlog"
-	log "============================="
-	call_pi_manage audit dump -f - -t 2d >> "$tempfile"
-}
-
-centos_auditlog() {
-	if [[ "$(getenforce)" == "Enforcing" ]]; then
-		log
-		log "SECTION: centOS Auditlog"
-		log "========================"
-		grep "denied" /var/log/audit/audit.log  >> "$tempfile"
-	fi
-}
-
-apache_log() {
-	if [[ "${OS}" == "centos" ]]; then
-		log
-		log "SECTION: httpd SSL_error_log"
-		log "============================"
-		tail -50 /var/log/httpd/ssl_error_log  >> "$tempfile"
-		log
-		log "SECTION: httpd Access_log"
-		log "============================"
-		tail -50 /var/log/httpd/ssl_access_log  >> "$tempfile"
-	else
-		log
-		log "SECTION: apache2 error_log"
-		log "============================"
-		tail -50 /var/log/apache2/error.log >> "$tempfile"
-		log
-		log "SECTION: apache2 SSL_access_log"
-		log "============================"
-		tail -50 /var/log/apache2/ssl_access.log >> "$tempfile"
-	fi
-}
-
 FreeRADIUS_config() {
 	log
 	log "SECTION: FreeRADIUS Configurations"
@@ -191,16 +150,81 @@ else
 fi
 }
 
+system_status() {
+	log
+	log "SECTION: System Status"
+	log "======================"
+	log "CPU cores: $(grep ^processor /proc/cpuinfo | wc -l)"
+	log "========================"
+	top -b -n 1 >> "$tempfile"
+	log "========================"
+	log "HD"
+	log "========================"
+	df -h >> "$tempfile"
+}
+
+centos_auditlog() {
+	if [[ "$(getenforce)" == "Enforcing" ]]; then
+		log
+		log "SECTION: centOS Auditlog"
+		log "========================"
+		grep "denied" /var/log/audit/audit.log  >> "$tempfile"
+	fi
+}
+
+apache_log() {
+	if [[ "${OS}" == "centos" ]]; then
+		log
+		log "SECTION: httpd SSL_error_log"
+		log "============================"
+		tail -50 /var/log/httpd/ssl_error_log  >> "$tempfile"
+		log
+		log "SECTION: httpd Access_log"
+		log "========================="
+		tail -50 /var/log/httpd/ssl_access_log  >> "$tempfile"
+		log
+		log "SECTION: apache configuration"
+		log "============================="
+		cat /etc/httpd/conf/httpd.conf  >>  "$tempfile"
+	else
+		log
+		log "SECTION: apache2 error_log"
+		log "=========================="
+		tail -50 /var/log/apache2/error.log >> "$tempfile"
+		log
+		log "SECTION: apache2 SSL_access_log"
+		log "==============================="
+		tail -50 /var/log/apache2/ssl_access.log >> "$tempfile"
+		log
+		log "SECTION: apache configuration"
+		log "============================="
+		cat /etc/apache2/apache2.conf  >>  "$tempfile"
+	fi
+}
+
+pi_logfile() {
+	R=$( grep "^PI_LOGFILE" "$PICFG" | cut -d "=" -f2 | tr -d "\'\"" )
+	[ -f ${R} ] && cp ${R} "${diag_info}/privacyidea.logfile" || echo "Could not read logfile ${R}" >> "$tempfile"
+}
+
+pi_auditlog() {
+	call_pi_manage audit dump -f - -t 2d >> "${diag_info}/privacyidea.auditlog"
+}
+
+
 get_os
 get_pi_cfg
 current_db_revision
 pi_versions
 pi_config
-pi_logfile
-pi_auditlog
-upload_info
+FreeRADIUS_config
+system_status
 if [[ "${OS}" == "centos" ]]; then
 	centos_auditlog
 fi
 apache_log
-FreeRADIUS_config
+pi_logfile
+pi_auditlog
+upload_info
+
+tar -zcf "/tmp/${timestamp}_$(basename "$diag_info").tar.gz" -C /tmp "$(basename "$diag_info")"
